### ISSUE TITLE
AIS Ships failure

### ISSUE THREAD

**Issue by EA8CXN** [ianrenton/planesailing-server#17]
Good day, 
I'm using the server for have the Json output but I can only see AIS SHORE STATIONS on the decoded data. In the Aisdispatcher I can see some vessels and on OpenCPN I can see them too, so Aisdispatcher is working but planesailing-server only decode Shore stations.

Any help would be appreciated.
Thanks

**Comment by ianrenton** [comment]
Hi, that is very strange! Are you able to check the log output from Plane Sailing Server to see if there are any exceptions reported? (The log will be output to stdout if you are running the application directly, or if you are running as a service on Linux you can use e.g. `journalctl -u planesailingserver`)

The log should also show a line every few minutes indicating what tracks are known to the system, do you have ships there or just AIS shore stations?

If there are no obvious problems in the Plane Sailing Server logs, then if you can capture the NMEA output of your AIS receiver (or rtl_AIS software) I can look at that and investigate why the software is not handling it correctly.

**Comment by EA8CXN** [comment]
Good day, 
Thanks for your fast reply.
I'm testing on 2 raspberry pi your software, they use the same Aisdispatcher. Also I have another soft OpenCpn working to check. The only setting that I change is the JSONoutput TRUE, because I really need that.
[example of nmea.txt](https://github.com/ianrenton/planesailing-server/files/8118677/example.of.nmea.txt)

As you can see on the picture, only AIS_SHORE stations are on the log, but not the vessel. In the current situation they are onle 2 vessels.
![image](https://user-images.githubusercontent.com/57015444/155183084-5be5866a-342f-4e26-ade9-b50d1bf2a361.png)

**Comment by EA8CXN** [comment]
Looking the log I found one exception:

Exception in thread "AIS handler thread" java.lang.NullPointerException
	at com.ianrenton.planesailing.comms.AISUDPReceiver.handle(AISUDPReceiver.java:127)
	at com.ianrenton.planesailing.comms.AISUDPReceiver.lambda$0(AISUDPReceiver.java:60)
	at dk.tbsalling.aismessages.nmea.NMEAMessageHandler.lambda$sendToAisMessageReceivers$0(NMEAMessageHandler.java:110)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dk.tbsalling.aismessages.nmea.NMEAMessageHandler.sendToAisMessageReceivers(NMEAMessageHandler.java:110)
	at dk.tbsalling.aismessages.nmea.NMEAMessageHandler.accept(NMEAMessageHandler.java:75)
	at dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader.run(NMEAMessageInputStreamReader.java:85)
	at dk.tbsalling.aismessages.AISInputStreamReader.run(AISInputStreamReader.java:57)
	at com.ianrenton.planesailing.comms.AISUDPReceiver$AISReceiver.run(AISUDPReceiver.java:298)
	at java.base/java.lang.Thread.run(Thread.java:829)
17:19:21 ERROR Exception in AIS Receiver
java.io.IOException: Read end dead
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:262) ~[?:?]
	at java.io.PipedInputStream.receive(PipedInputStream.java:226) ~[?:?]
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:122) ~[?:?]
	at com.ianrenton.planesailing.comms.AISUDPReceiver$UDPReceiver.run(AISUDPReceiver.java:278) [plane-sailing-server-2.5.4-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
17:19:23 INFO  Track table contains: 3 AIS_SHORE_STATION   2 APRS_MOBILE   1 APRS_BASE_STATION   1 BASE_STATION   1 AIRPORT   1 SEAPORT   
17:19:23 INFO  ----------------------------------------------------------------------------------
17:19:23 INFO  Name                 Type       Description                               Age (ms)
17:19:23 INFO  ----------------------------------------------------------------------------------
17:19:23 INFO  EL PASO              AIS_SHORE_                                           11707 
17:19:23 INFO  SCT                  SEAPORT                                              180204
17:19:23 INFO  MMSI 2241077         AIS_SHORE_                                           16710

**Comment by ianrenton** [comment]
Version 2.5.5 is available now, please try upgrading to it and see if it solves your problem!
